// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package skeleton

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"preload\" href=\"/assets/fonts/Sans.woff2\" as=\"font\" type=\"font/woff2\" crossorigin><link rel=\"preload\" href=\"/assets/fonts/Mono.woff2\" as=\"font\" type=\"font/woff2\" crossorigin><link rel=\"stylesheet\" href=\"/assets/css/franken-ui@2.0.0/core.min.css\"><script src=\"/assets/js/franken-ui@2.0.0/core.iife.js\"></script><script src=\"/assets/js/franken-ui@2.0.0/icon.iife.js\"></script><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout/skeleton/header.templ`, Line: 12, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script>\n\t\t\tconst htmlElement = document.documentElement;\n\n\t\t\tconst __FRANKEN__ = JSON.parse(localStorage.getItem('__FRANKEN__') || '{}');\n\n\t\t\tif (\n\t\t\t\t__FRANKEN__.mode === 'dark' ||\n\t\t\t\t(!__FRANKEN__.mode && window.matchMedia('(prefers-color-scheme: dark)').matches)\n\t\t\t) {\n\t\t\t\thtmlElement.classList.add('dark');\n\t\t\t} else {\n\t\t\t\thtmlElement.classList.remove('dark');\n\t\t\t}\n\n\t\t\thtmlElement.classList.add(__FRANKEN__.theme || 'uk-theme-zinc');\n\t\t\thtmlElement.classList.add(__FRANKEN__.radii || 'uk-radii-md');\n\t\t\thtmlElement.classList.add(__FRANKEN__.shadows || 'uk-shadows-sm');\n\t\t\thtmlElement.classList.add(__FRANKEN__.font || 'uk-font-sm');\n\t\t\thtmlElement.classList.add(__FRANKEN__.chart || 'uk-chart-base');\n\t\t</script></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
